name: flutter_provider_rx
description: Flutter provider rx design pattern

publish_to: 'none' # Remove this line if you wish to publish to pub.dev

version: 1.0.0+1

environment:
  sdk: ">=2.7.0 <3.0.0"

dependencies:
  flutter:
    sdk: flutter
  flutter_localizations:
    sdk: flutter

  cupertino_icons: ^1.0.0
  provider: ^5.0.0
  rxdart: ^0.26.0
  connectivity: ^3.0.3 # network status
  flutter_spinkit: ^5.0.0 # custom loading in app
  animations: ^2.0.0 # animations for UX
  platform_action_sheet: ^0.0.3
  dio: ^3.0.10 # service + api
  url_launcher: ^6.0.2 # launcher url
  image: ^3.0.2
  hive: ^2.0.0
  path_provider: ^2.0.1
  fl_chart: ^0.36.1
  get_it: ^7.2.0 # DI
  go_router: ^3.0.7

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^1.0.4


flutter:
  uses-material-design: true
  assets:
    - assets/drawables/icons/
    - assets/drawables/icons/2x/
    - assets/drawables/icons/3x/
  fonts:
    - family: Montserrat
      fonts:
        - asset: assets/fonts/Montserrat_Bold.ttf
          weight: 700


flutter_intl:
  enabled: true
