name: flutter_provider_rx
description: Flutter provider rx design pattern

publish_to: 'none' # Remove this line if you wish to publish to pub.dev

version: 1.0.0+1

environment:
  sdk: ">=2.7.0 <3.0.0"

dependencies:
  flutter:
    sdk: flutter
  flutter_localizations:
    sdk: flutter

  cupertino_icons: ^1.0.0
  provider: ^4.3.3
  rxdart: ^0.25.0
  connectivity: ^2.0.1 # package listen network status
  flutter_spinkit: ^4.1.2+1 # loading ui in app
  toast: ^0.1.5 # show toast in app
  animations: ^1.1.2 # animation for UX
  platform_action_sheet: ^0.0.3
  dio: ^3.0.10 # service + api
  url_launcher: ^5.7.10 # launcher url
  image: ^2.1.19
  hive: ^1.4.4+1
  path_provider: ^1.6.24

dev_dependencies:
  flutter_test:
    sdk: flutter


flutter:
  uses-material-design: true
  assets:
    - assets/drawables/icons/
    - assets/drawables/icons/2x/
    - assets/drawables/icons/3x/
  fonts:
    - family: Montserrat
      fonts:
        - asset: assets/fonts/Montserrat_Bold.ttf
          weight: 700


flutter_intl:
  enabled: true
